쿼리 메소드 기능 > JPA NamedQuery
"쿼리에 이름을 부여하고 호출하는 기능"

JPA의 NamedQuery를 호출할 수 있음
* `@NamedQuery` 어노테이션으로 Named 쿼리 정의

실무에서 이 방법을 거의 사용을 안하기 때문에 쓸 일이 없다. 왜냐하면 엔티티가 아닌 리포지토리에 바로 쿼리를 지정할 수 있는 방법이 있기 때문에 그 방법을 선호한다.

다만 NamedQuery가 지닌 가장 큰 장점이 하나가 있다
쿼리 문자열에 typo가 있을 경우 애플리케이션 로딩 시점에 쿼리에 대해 파싱을 해보고, 오류가 있으면 문법 오류를 에러 메세지로 알려준다
````
Caused by: org.hibernate.HibernateException: Errors in named queries:
org.hibernate.QueryException: could not resolve property: usernasdfasdfame
````
NamedQuery는 기본적으로 정적 쿼리이기 때문에 애플리케이션 로딩 시점에 이 쿼리를 모두 파싱을 해볼 수 있다. 그래서 JPQL을 SQL로 미리 만들어 놓는 과정을 거치면서 개발자에게는 애플리케이션 로딩 시점에 버그를 잡을 수 있는 포인트를 제공한다

-----

Spring Data JPA가 제공하는 마법 같은 기능

쿼리 메소드 기능 3가지
* 메소드 이름으로 쿼리 생성
* 메소드 이름으로 JPA NamedQuery 호출
* `@Query` 애노테이션을 사용해서 리파지토리 인터페이스에 쿼리 직접 정의